ArmorOverhaul.options.gui_enabled="true"
ArmorOverhaul.options.gui_health="true"
ArmorOverhaul.options.debug="false"
ArmorOverhaul.options.gui_armor="true"
ArmorOverhaul.options.lang="en"
ArmorOverhaul.options.localize="true"
